### PR TITLE
Return error from NewConsumer if consumer.Subscribe() fails

### PR DESCRIPTION
**Pull request by ryan0x44**
consumer.Subscribe() will return an error if it fails to register the consumer, but without this change it will not be returned from NewConsumer() so there is no way for the calling code to know about the error.

Also, I ran goimports prior to making the change to fix the code format :)

### CODE REVIEW

**Comment by sasha-alias** [comment]
Thanks for PR,
Unfortunately there are no automated tests yet, so review can take a bit of time.

**Comment by ryan0x44** [comment]
Glad to help!

The changes functional change is quite small:
https://github.com/sasha-alias/pgq/pull/1/commits/9908e6adc84851323cf240bba160413c0d4d695d

The full diff for this PR looks quite big, however, because running goimports lints the code and does a lot of reformatting;
https://github.com/sasha-alias/pgq/pull/1/commits/c7a885dc18e5a05addd0f10654f2008a156f9ea2

**Comment by sasha-alias** [comment]
sorry for long delay, merging essential part of the pull request, skipping the reformatting part

**Comment by ryan0x44** [comment]
@sasha-alias skipping reformatting makes it difficult to contribute, as gofmt/goimports formatting is a pretty standard thing in the Go community - code I create a PR to handle reformatting?

**Pull request closed without merging**
